// src/app/(app)/template.js
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import { getServerSession } from "next-auth";
import { Lato } from "next/font/google";
import "../globals.css";
import { Toaster } from "react-hot-toast";
import { redirect } from "next/navigation";

const lato = Lato({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Biolinkhq by itsnicbtw",
  description: "Generated by create next app",
};

export default async function AppTemplate({ children }) {
  // Ensure the user is authenticated; redirect if not
  const session = await getServerSession(authOptions);
  if (!session) {
    redirect("/");
  }

  return (
    <html lang="en" className="dark">
      <body className={`${lato.className} bg-[#0b0f14] text-gray-100`}>
        <Toaster />
        {/* Full‑width container without sidebar */}
        <main className="min-h-screen">{children}</main>
      </body>
    </html>
  );
}
