import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import { Page } from "@/models/Page";
import { faArrowLeft, faChartLine, faCreditCard, faFileLines } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import mongoose from "mongoose";
import { getServerSession } from "next-auth";
import { Lato } from "next/font/google";
import "../globals.css";
import Image from "next/image";
import Link from "next/link";
import { redirect } from "next/navigation";
import { Toaster } from "react-hot-toast";
import LogoutButton from "@/components/buttons/LogoutButton";

const lato = Lato({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Biolinkhq by itsnicbtw",
  description: "Generated by create next app",
};

function navClass(active) {
  return active
    ? "flex items-center gap-3 rounded-xl px-4 py-3 text-blue-400 bg-blue-500/10 font-bold"
    : "flex items-center gap-3 rounded-xl px-4 py-3 text-gray-400 hover:bg-white/5 hover:text-white transition";
}

export default async function AppTemplate({ children }) {
  const session = await getServerSession(authOptions);

  if (!session) {
    redirect("/");
  }

  await mongoose.connect(process.env.MONGO_URI);

  const email = (session.user.email || "").toLowerCase().trim();
  const page = await Page.findOne({ owner: email }).lean();

  const showSubscription =
    page?.permanentPlan === "exclusive" ||
    ["active", "trialing", "past_due"].includes(
      String(page?.stripeSubscriptionStatus || "").toLowerCase()
    );

  const avatar = session.user.image || "/assets/logo.webp";

  return (
    <html lang="en" className="dark">
      <body className={`${lato.className} bg-[#0b0f14] text-gray-100`}>
        <Toaster />

        <main className="min-h-screen md:flex">
          <aside className="w-full border-r border-white/10 bg-white/[0.03] px-6 py-8 md:min-h-screen md:w-[260px]">
            <div className="sticky top-0">
              <div className="mx-auto h-24 w-24 overflow-hidden rounded-full bg-white/5">
                <Image
                  src={avatar}
                  width={256}
                  height={256}
                  alt="avatar"
                  className="h-full w-full object-cover"
                />
              </div>

              {page ? (
                <Link
                  target="_blank"
                  href={`/${page.uri}`}
                  className="mt-5 flex items-center justify-center gap-2 text-center"
                >
                  <Image
                    src="/assets/logo.webp"
                    alt="logo"
                    height={24}
                    width={24}
                  />
                  <span className="text-xl text-gray-500">/</span>
                  <span className="font-bold hover:underline">{page.uri}</span>
                </Link>
              ) : null}

              <nav className="mx-auto mt-8 flex max-w-[220px] flex-col gap-2">
                <Link href="/account" className={navClass(false)}>
                  <FontAwesomeIcon icon={faFileLines} fixedWidth className="h-5 w-5" />
                  <span>My Page</span>
                </Link>

                <Link href="/account/analytics" className={navClass(false)}>
                  <FontAwesomeIcon icon={faChartLine} fixedWidth className="h-5 w-5" />
                  <span>Analytics</span>
                </Link>

                {showSubscription ? (
                  <Link href="/account/subscription" className={navClass(false)}>
                    <FontAwesomeIcon icon={faCreditCard} fixedWidth className="h-5 w-5" />
                    <span>Subscription</span>
                  </Link>
                ) : null}

                <LogoutButton
                  iconLeft
                  className="flex items-center gap-3 rounded-xl px-4 py-3 text-gray-400 hover:bg-white/5 hover:text-white transition"
                  iconClasses="h-5 w-5"
                />

                <Link
                  href="/"
                  className="mt-4 flex items-center gap-2 border-t border-white/10 pt-4 text-xs text-gray-500 hover:text-white transition"
                >
                  <FontAwesomeIcon icon={faArrowLeft} className="h-3 w-3" />
                  <span>Back to website</span>
                </Link>
              </nav>
            </div>
          </aside>

          <div className="min-w-0 flex-1">{children}</div>
        </main>
      </body>
    </html>
  );
}
